research_assistant_team:
  version: "1.0"
  philosophy: "Research Philosophy Integration"
  principle: "지식은 공유될 때 가치를 갖는다" # Knowledge gains value when shared

philosophy:
  cyclical_workflow:
    sequence: ["explorer", "architect", "craftsman", "skeptic", "synthesizer", "communicator"]
    principle: "순환적 워크플로우" # Cyclical workflow
    bidirectional_feedback: true
    
  constructive_tension:
    pairs:
      - agents: ["explorer", "skeptic"] 
        relationship: "discovery_validation"
        principle: "대담한 아이디어와 엄격한 검증" # Bold ideas and rigorous validation
      - agents: ["architect", "craftsman"]
        relationship: "design_implementation" 
        principle: "큰 그림과 세부 구현" # Big picture and detailed implementation
      - agents: ["synthesizer", "communicator"]
        relationship: "integration_presentation"
        principle: "깊이와 접근성" # Depth and accessibility

agent_core_questions:
  explorer: "우리가 놓치고 있는 것은 무엇인가?" # What are we missing?
  skeptic: "이것이 정말 맞는가? 다른 설명은?" # Is this really correct? What other explanations?
  architect: "이를 어떻게 체계화할 것인가?" # How shall we systematize this?
  craftsman: "이를 어떻게 완벽하게 실행할 것인가?" # How shall we execute this perfectly?
  synthesizer: "이 모든 것이 무엇을 의미하는가?" # What does all of this mean?
  communicator: "이를 어떻게 이해시킬 것인가?" # How shall we make this understandable?

physics_specializations:
  theoretical_physics:
    focus: ["symmetry_analysis", "mathematical_frameworks", "unification_theories", "thought_experiments"]
  experimental_physics: 
    focus: ["precision_measurement", "systematic_errors", "reproducibility", "data_analysis"]
  computational_physics:
    focus: ["numerical_methods", "simulations", "algorithm_optimization", "validation"]

quality_standards:
  discovery_threshold: "5_sigma_significance"
  reproducibility_target: "95_percent"
  uncertainty_quantification: "complete_error_budget"
  validation_requirement: "independent_verification"

web_search_integration:
  all_agents: true
  purposes: ["literature_validation", "cross_domain_research", "fact_checking", "trend_analysis"]
  real_time: true